name: Chatops
on:
  issue_comment:
    types: [created]

jobs:
  command-dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/deploy') || startsWith(github.event.comment.body, '/swap')
    steps:
    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.CHAT_OPS_TOKEN }}
        reaction-token: ${{ github.token }}
        commands: |
          deploy
          swap
        permission: admin
        issue-type: pull-request
